name: test_project
description: https://jsonplaceholder.typicode.com/

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  hive: 2.2.3
  hive_flutter: 1.1.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: 1.1.3
  build_runner: 2.2.0
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
